### ISSUE TITLE
cda_query not documented

### ISSUE THREAD

**Issue by Naatan** [contentful-labs/contentful_middleman#15]
Neither here nor in contentful.rb

**Comment by madtrick** [comment]
Do you mean the [query parameter](https://www.contentful.com/developers/documentation/content-delivery-api/#search-filter-full-text)?

**Comment by Naatan** [comment]
I'm not sure, you tell me? :p

I'm talking about `cda_query` mentioned in https://github.com/contentful-labs/contentful_middleman/blob/master/README.md

(ctrl+F - `cda_query`)

**Comment by madtrick** [comment]
Ah sorry, I get it now. You have an example of the `cda_query` option [in the README](https://github.com/contentful-labs/contentful_middleman/blob/master/README.md#configuration-examples) and it's also described in the [usage section](https://github.com/contentful/contentful.rb#usage) of the https://github.com/contentful/contentful.rb gem (search for `client.entries`)

**Comment by Naatan** [comment]
I see, that's not exactly intuitive though. When I'm being directed to another page for documentation on `cda_query` I do not expect the terminology to change and be expected to read the entire page to figure out what it may connect to. I'd suggest adding something like "referred to as client.entries" to your readme here.

**Comment by madtrick** [comment]
Yep, that's a great idea. Will do that! and thanks for your feedback
