### ISSUE TITLE
Is there a way to get unpublished articles?

### ISSUE THREAD

**Issue by Naatan** [contentful-labs/contentful_middleman#24]
It'd be nice if I could pull in unpublished articles so I can test them on a dev/QA environment before "publishing" them. Is this possible with this extension?

**Comment by pxlpnk** [comment]
The current master includes the ability to set `use_preview_api` to `true` this will allow you to see unpublished articles. 
See also the documentation for it: https://www.contentful.com/developers/documentation/content-delivery-api/http/#preview-api

**Comment by madtrick** [comment]
@Naatan any update on this?

**Comment by Naatan** [comment]
Sorry I was so busy when I posted this I didnt even remember to report back.

The suggestion @pxlpnk gave works fine, just update to the master branch.
