### ISSUE TITLE
OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by netlify-user-nomads** [contentful-labs/contentful_middleman#25]
I am working on windows 8 64 bit machine. 

When I write the following command I get this error "middleman contentful"

C:/Ruby193/lib/ruby/gems/1.9.1/gems/http-0.8.1/lib/http/timeout/null.rb:23:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)

Can anybody help me with this ?

**Comment by pxlpnk** [comment]
It seems Windows does not deliver proper SSL certs to validate against.
You should be able to use the one that curl provides you.
See this link: https://gist.github.com/fnichol/867550#the-manual-way-boring
You have to adjust the place where you put the `cacert.pem` file.

**Comment by madtrick** [comment]
@netlify-user-nomads any update on this?

**Comment by madtrick** [comment]
@netlify-user-nomads I'm going to close this. If you have any more issues please feel free to reopen it.
