### ISSUE TITLE
Default config options only fetch 100 entries

### ISSUE THREAD

**Issue by tdreyno** [contentful-labs/contentful_middleman#33]
This seems like an oversight since the expectation of this plugin is that it'd fetch the entire data set and serialize it.

**Comment by neonichu** [comment]
This is true. You can use the `cda_query` to fetch more entries (up to 1000) like this:

```ruby
activate :contentful do |f|
  f.space         = {partners: 'space-id'}
  f.access_token  = 'some_access_token'
  f.cda_query     = { content_type: 'content-type-id', include: 1, limit: 1000 }
  f.content_types = { partner: 'content-type-id'}
end
```

**Comment by tdreyno** [comment]
Cool. Feel free to close this if it's just a documentation issue.
