### ISSUE TITLE
How to import multiple content types

### ISSUE THREAD

**Issue by vishu099** [contentful-labs/contentful_middleman#35]
I have created multiple content types in my contentful and would like to get that data into my middleman. 

Please suggest me how can I do so ?

**Comment by neonichu** [comment]
You can remove the content-type filter from the `cda_query` parameter and define multiple mappings for all your content-types. This would look somewhat like this:

```ruby
activate :contentful do |f|
  f.space         = {partners: 'space-id'}
  f.access_token  = 'some_access_token'
  f.cda_query     = { include: 1 }
  f.content_types = { partner: 'content-type-id', post: 'post-content-type-id' }
end
```
