### ISSUE TITLE
Multiple mappers

### ISSUE THREAD

**Issue by nijotz** [contentful-labs/contentful_middleman#36]
Being able to provide a list of mappers for a content type would be helpful.  I have a mapper that adds the 'sys' data from Contentful to the YAML files (I need updated/created timestamps).  I also have a mapper that adds back-references to the YAML files.  It would be nice to provide these mappers as a list.  To work around this, I've had to pull out these two different mapping functions and create mapper classes that call one or the other or both.

**Comment by dlitvakb** [comment]
@nijotz Can you explain a bit better what you're trying to accomplish?

For what I understand, what you want could be accomplished by using a Composite Mapper, something like this

```ruby
class CompositeEntryMapper < ContentfulMiddleman::Mapper::Base
  @@mappers = []
  def self.mappers
    @@mappers
  end

  def map(context, entry)
    super
    mappers.each do |m|
      m.map(context, entry)
    end
  end
end
```

Then in your config.rb file:

```ruby
CompositeMapper.mappers << YourMapper.new
CompositeMapper.mappers << OtherMapper.new

activate :contentful do |f|
  '... your config here ...'
  f.content_types = {content_type_name_you_want_to_map: {mapper: CompositeMapper, id: 'content_type_id'}}
end
``` 

Please let me know if this helps

**Comment by nijotz** [comment]
Nice, I ended up doing something similar.  Figured having this kind of functionality built-in, in the docs, and/or in the examples would be helpful.  Thanks!

**Comment by dlitvakb** [comment]
Hey @nijotz,

Thanks on the input, I'll add more information on this on the README
