### ISSUE TITLE
MultiLingual

### ISSUE THREAD

**Issue by vishu099** [contentful-labs/contentful_middleman#38]
I have enabled localization in my contentful account. Can anyone guide me how can I have multi-lingual content in my contentful middleman

**Comment by neonichu** [comment]
You can select the locale you want to fetch via the `cda_query` parameter:

```ruby
f.cda_query     = { include: 1, locale: 'de-DE' }
```

**Comment by vishu099** [comment]
This way I am able to fetch one language content but I want to fetch both the contents like in ENGLISH as well as in GERMAN

**Comment by neonichu** [comment]
This isn't easily possible, because the CDA will only ever serve one locale per request. 

You could try activating the extension multiple times with different `cda_query` parameters for the same space, but I'm unsure what the result would be.

**Comment by vishu099** [comment]
Can you please give me an example of what you are asking me to do ?

**Comment by neonichu** [comment]
Basically have two of the configuration blocks described in this section <https://github.com/contentful-labs/contentful_middleman#configuration> in your middleman configuration, each with different `locale` parameters in the `cda_query`.

**Comment by vishu099** [comment]
I have tried that option but that fetches the data of the last configuration block

**Comment by neonichu** [comment]
Sorry, then this use case is not supported at this point.

**Comment by dagumak** [comment]
@neonichu So if I have 2 locales, then I should have to activate blocks for contentful? How do I target the correct locale if the data is mixed? Is there a way to separate the data into different paths?
