### ISSUE TITLE
New Feature Request - Multilingual Support

### ISSUE THREAD

**Issue by vishu099** [contentful-labs/contentful_middleman#39]
Can we add a new feature in contentful middleman to get two languages at the same time from contentful. 

The issues I am facing is that I have added a content in 2 different languages in the contentful and now  I would like to get both the language content.

Current there is no way possible in which I can fetch both the content

I even tried this but it doesn't work

activate :contentful do |f|
  f.space         = {Sample: 'xxxxxxxxxxl1'}
  f.access_token  = '1axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb9bf935d6ca1'
  f.cda_query     = { include: 1,locale: 'en-US' }
  f.content_types = { Sample: '6kxxxxxxxxxxxxxxxx02ME'}
end

activate :contentful do |f|
  f.space         = {Sample: 'xxxxxxxxxxl1'}
  f.access_token  = '1axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxb9bf935d6ca1'
  f.cda_query     = { include: 1,locale: 'de-DE' }
  f.content_types = { Sample: '6kxxxxxxxxxxxxxxxx02ME'}
end

Thanks

**Comment by jeromegn** [comment]
This feature would make me switch to using contentful.

**Comment by dlitvakb** [comment]
@vishu099 @jeromegn This will be available once [contentful/#72](https://github.com/contentful/contentful.rb/pull/72) gets merged and released.

For allowing that, in the CDA Query, you need to specify `locale: "*"`

Thank you very much for your feedback.

Please let us know if this helped
