### ISSUE TITLE
Add warning when limit is reached

### ISSUE THREAD

**Issue by Naatan** [contentful-labs/contentful_middleman#40]
I just spend half an hour trying to figure out why my new content wasnt showing up. Ended up being this: https://github.com/contentful-labs/contentful_middleman/commit/8e4c4010f6fecac7e95010306b4a6ac6bf4ef300

**Comment by nijotz** [comment]
:+1:

**Comment by dlitvakb** [comment]
Hi @Naatan,

This should be solved with the merge of #52

**Comment by dlitvakb** [comment]
As #52 is now merged, you should be able to add `f.all_entries = true` in your `activate :contentful` block in `config.rb`
