### ISSUE TITLE
Handle more than 1000 entries

### ISSUE THREAD

**Issue by nijotz** [contentful-labs/contentful_middleman#45]
You can't activate the contentful_middleman extension multiple times to get more than 1000 entries, because it will remove the existing YAML files.  I had to modify contentful_middleman to allow more than 1000 entries:
https://github.com/Instrument/contentful_middleman/commit/c0313de2fecc70e7d27dbab52bbd9b61196dca6f

**Comment by neonichu** [comment]
Would be cool if you could make a PR out of that commit :)

**Comment by nijotz** [comment]
Thanks @dlitvakb!
