### ISSUE TITLE
Mapping Entries to Middleman::Sitemap::Resource objects

### ISSUE THREAD

**Issue by jordanandree** [contentful-labs/contentful_middleman#54]
I'm wondering if there would be benefit in a feature that allows Contentful Entries to be mapped to [Middleman `Sitemap::Resource`](https://middlemanapp.com/advanced/sitemap/#sitemap-resources) objects for passing off to templates and use across other middleman features. In my use case, I have a Content Type named `Article` for a blog that I want to built out individually and on an index page.

I have some code written that involves taking Contentful Entry mappings (that this gem provides) and adds them into `Middleman::Sitemap::Store`. A couple of configuration things that I'm considering in my implementation:

- A Contentful `Sitemap::Resource` needs to know about the Entry fields it should respond to and should be configurable in the extension. I'm thinking of this would function the same as [Frontmatter](https://middlemanapp.com/basics/frontmatter/)
- Collections of these `Sitemap::Resource` objects could be accessible at the global app level by use of `app.set` (and further, [collections in Middleman v4](https://github.com/middleman/middleman/pull/1307))
- A required template in `source` would be required for the Entries to be rendered to (might be able to have "logical" `Sitemap::Resource` objects)

Happy to open a PR for review if it would help! Also, not sure if this functionality is already in the works for a future release. Didn't see anything in this repo for it, so thought it was worth a mention :)

**Comment by grncdr** [comment]
Hey @jordanandree that's indeed a pretty good idea, and one of our developers implemented something like that in [`contentful-middleman-pages`](https://github.com/contentful/contentful-middleman-pages/blob/master/lib/contentful/middleman-pages/extension.rb#L82-L104).

Unfortunately `contentful-middleman-pages` isn't totally finished, and sits a little bit lower on the priority list for us at the moment. If you wanted to use it as a starting point and send PR's to fill in the functionality you're missing that would be totally awesome :heart:

**Comment by jordanandree** [comment]
oh interesting! looks like contentful-middleman-pages might get me the functionality i need. I'll take a look at it and see! thanks!
